### ISSUE TITLE
Linux subsystem install instructions

### ISSUE THREAD

**Issue by bnates** [codefellows/code-401-JS-prework#10]

**Comment by michaeltreat** [comment]
I have some docs made for this:

https://gist.github.com/michaeltreat/a1906898ede3cac7b833c4a2afdc58c4

It's a bit lengthy, but It's a good starting point.

**Comment by michaeltreat** [comment]
@bnates I made a guide on this topic. I think this is what you're looking for:

https://github.com/michaeltreat/Windows-Subsystem-For-Linux-Setup/blob/master/readmes/01_preface.md

Also, I made a PR into the 201 prework repo to include this guide for the Windows specific prework section.

Let me know what you think!
