### ISSUE TITLE
Install: telnet

### ISSUE THREAD

**Issue by johncokos** [codefellows/code-401-JS-prework#15]

**Comment by JudyVue** [comment]
@johncokos @bnates What is the context of this? For Lab 6? Mac users should not be using netcat?

**Comment by johncokos** [comment]
Either app is fine, really. If netcat is more modern/standard, then lets go with that.

I think you still have to do a step to install it, though.

**Comment by michaeltreat** [comment]
Windows users also have issues with telnet, but if they follow the WSL guide it naturally fixes it.

**Comment by dahlbyk** [comment]
Non-WSL option: run PowerShell as Administrator and:

```powershell
Enable-WindowsOptionalFeature -Online -FeatureName TelnetClient
```
