### ISSUE TITLE
Integrate ES6Katas as Prework

### ISSUE THREAD

**Issue by bnates** [codefellows/code-401-JS-prework#16]
Let's identify which challenges from this we'd like to roll into prework:

http://es6katas.org/

**Comment by johncokos** [comment]
Open Questions:

Which ones should students be required to do?
How do they turn it in?

Working session needed to select, copy, paste into a new repo.

Consider making a new repo for them to fork that they would pull down that would serve as their code challenges folder for DSA stuff too ...

**Comment by johncokos** [comment]
promises
arrow functions
block scope
object literal
array 
template strings
string

**Comment by johncokos** [comment]
Find some room for this as pre-reading/browsing

http://es6-features.org/#RestParameter
