### ISSUE TITLE
Editor Configuration Settings

### ISSUE THREAD

**Issue by bnates** [codefellows/code-401-JS-prework#21]
@sjschmidt44 can you comment with your editor config file, please?

**Comment by sjschmidt44** [comment]
[EditorConfig](https://editorconfig.org)

The following goes in a `.editorconfig` file, which should be in the root of any project; just like an `eslintrc.json`:

```
# http://editorconfig.org

root = true

[*]
indent_style = space
indent_size = 4
insert_final_newline = true
trim_trailing_whitespace = true
end_of_line = lf
charset = utf-8

# Docstrings and comments use max_line_length = 79
[*.py]
max_line_length = 119

# Use 2 spaces for the HTML files
[*.{html, js, css, yml, jinja2, json}]
indent_size = 2```

**Comment by agrampa** [comment]
https://github.com/codefellows/code-201-guide/issues/252

Discussed today in 201 sync

**Comment by johncokos** [comment]
Are there any special "use it" instructions for individual editors?  If so, document.

**Comment by dahlbyk** [comment]
https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig
