### ISSUE TITLE
Revised instructions for Watchman installation

### ISSUE THREAD

**Issue by dlchambersjr** [codefellows/code-401-JS-prework#29]
The instructions on the Watchman page via the link included in the NVM and Node readme seem to be incomplete.  After working through the process several times, I have concluded that the following steps can be used to install Watchman on a windows machine.  This may also work for other systems too.  They are adapted from this article, "Installing watchman on Ubuntu 18.04" ( https://medium.com/@saurabh.friday/install-watchman-on-ubuntu-18-04-ba23c56eb23a):

``` 
cd ~
git clone https://github.com/facebook/watchman.git
cd watchman/
git checkout v4.9.0
sudo apt-get install -y autoconf automake build-essential python-dev
sudo apt-get install libtool
sudo apt-get install libssl-dev
Sudu apt install pkg-config
./autogen.sh 
./configure
make
sudo make install
watchman --version

```

**Comment by johncokos** [comment]
This might be a non-issue ... I think React Native does this for you. Will investigate

**Comment by dlchambersjr** [comment]
Thanks, John!

David
